### ISSUE TITLE
each/else in pug does not work correctly with signals

### ISSUE THREAD

**Issue by fcbvirus0k** [startupjs/startupjs#1198]
в паге не работает each/else если юзать результат `useQuery$` как массив по которому бежать надо, всегда в `else` уходит, даже если есть данные в результате квери
в примере ниже всегда будет показываться текст из `else` блока

```
const $players = useQuery$('players', { gameId })
return pug`
  each $player in $players
    Player($player=$player)
  else
    Span No players
`
```

**Comment by cray0000** [comment]
fixed
