### ISSUE TITLE
react-sharedb-hooks standalone usage?

### ISSUE THREAD

**Issue by jamesopti** [startupjs/startupjs#529]
I'd like to use the [react-sharedb-hooks](https://github.com/startupjs/startupjs/tree/master/packages/react-sharedb-hooks) package on it's own without startupjs, as I have an application already running with React and sharedb.

When I try to call `init`, I get a compilation error that `/lib/useBackPress.js` requires react-native.

Am I doing something wrong here?

Example:

```ts
import React, { useEffect, useState } from 'react'
import { Flex } from '@chakra-ui/react'
import ReconnectingWebSocket from 'reconnecting-websocket'

import init from 'startupjs/init'
import racer from 'racer'
import { observer, useDoc } from 'startupjs'

import config from 'config'

racer.Model.prototype._createSocket = function (bundle) {
  console.log(
    '[racer.Model.prototype._createSocket] ReconnectingWebSocket setup'
  )
  const wsProtocol = window.location.protocol.startsWith('https') ? 'wss' : 'ws'
  const socket = new ReconnectingWebSocket(
    `${wsProtocol}://${config('WS_HOST')}`
  )
  return socket
}

init({ baseUrl: config('WS_HOST') })

const RacerDemo = () => {
  const [user, $user] = useDoc('users', 'user-100')
  return (
    <Flex>
      <h1>Racer Demo</h1>
      <h2>User: {user.name}</h2>
    </Flex>
  )
}

export default observer(RacerDemo)

```

**Comment by pturchik** [comment]
You should use packages directly.

```js
import init from '@startupjs/init'
import { observer, useDoc } from '@startupjs/react-sharedb'
...
`

**Comment by jamesopti** [comment]
OK This got me past that `useBackPress` error! Thanks

However, `init` is not initializing the socket connection seemingly because the default export is the server package.

if i import the web init specifically (`import init from '@startupjs/init/lib/web'`), for some reason, my `_createSocket` method is not being used.

**Comment by cray0000** [comment]
Maybe you have multiple versions of `racer`? Try doing `yarn list racer` or `npm list racer`.

You might have another version specified in your project's `package.json`, different fron the one used by `react-sharedb` (https://github.com/startupjs/startupjs/blob/master/packages/init/package.json#L17). So make sure you specify the same versions in your project.

**Comment by cray0000** [comment]
same goes for `sharedb` dependency. There should also be only one of it.

**Comment by jamesopti** [comment]
> Maybe you have multiple versions of `racer`? Try doing `yarn list racer` or `npm list racer`.
> 
> You might have another version specified in your project's `package.json`, different from the one used by `react-sharedb` (https://github.com/startupjs/startupjs/blob/master/packages/init/package.json#L17). So make sure you specify the same versions in your project.

This was it! Thanks @cray0000 

I had added `racer` to my root package and that got version 1.0.0.
