### ISSUE TITLE
Upgrade to Racer 1.0.0 for better performance

### ISSUE THREAD

**Issue by jamesopti** [startupjs/startupjs#531]
The latest release of Racer ([v1.0.0](https://github.com/derbyjs/racer/releases/tag/v1.0.0)) provides performance updates and is largely backward compatible.

Are there plans to upgrade all of startupjs to use this version?

**Comment by cray0000** [comment]
Sure, we'll test it soon and if there are no breaking changes, we'll release a new patch version. Thanks for the heads up!

**Comment by pturchik** [comment]
@jamesopti we updated racer to 1.0.0 version in 0.33.0
